server:
  port: 8081

spring:
  application:
    name: ms_agendamiento

  datasource:
    url: jdbc:mysql://localhost:3306/db_ms_agendamiento?createDatabaseIfNotExist=true
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /doc/swagger-ui/index.html
  api-docs:
    path: /api-docs
