server:
  port: 0
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /agendamiento/api-docs 
  packages-to-scan: com.example.ms_agendamiento.controller 
  hateoas:                  
    enabled: false          

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka/} 
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

spring:
  application:
    name: MS-AGENDAMIENTO
  profiles:
    active: dev
  cloud:
    compatibility-verifier:
      enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origin-patterns: "*"
          allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
          allowed-headers: "*"
          exposed-headers: "*"
          allow-credentials: false
          max-age: 3600

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/db_plenamente?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ''
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: root
    url: jdbc:mysql://${DATABASE_HOST:mariadb-db}:3306/db_agendamiento_test?createDatabaseIfNotExist=true 
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    url: jdbc:mysql://mariadb-db:3306/db_agendamiento?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'root_password'
  jpa:
    hibernate:
      ddl-auto: none