server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # AGENDAMIENTO
        - id: reserva-service
          uri: lb://MS-AGENDAMIENTO
          predicates:
            - Path=/api/v1/reservas/**

        - id: boleta-service
          uri: lb://MS-AGENDAMIENTO
          predicates:
            - Path=/api/v1/boletas/**

        # PACIENTES
        - id: paciente-service
          uri: lb://MS-PACIENTES
          predicates:
            - Path=/api/v1/pacientes/**

        - id: diagnostico-service
          uri: lb://MS-PACIENTES
          predicates:
            - Path=/api/v1/diagnosticos/**

        - id: historial-service
          uri: lb://MS-PACIENTES
          predicates:
            - Path=/api/v1/historiales/**

        - id: prevision-service
          uri: lb://MS-PACIENTES
          predicates:
            - Path=/api/v1/prevision/**

        # PROFESIONALES
        - id: psicologo-service
          uri: lb://MS-PROFESIONALES
          predicates:
            - Path=/api/v1/psicologos/**

        - id: especialidad-service
          uri: lb://MS-PROFESIONALES
          predicates:
            - Path=/api/v1/especialidades/**

        - id: comuna-service
          uri: lb://MS-PROFESIONALES
          predicates:
            - Path=/api/v1/comunas/**

        - id: region-service
          uri: lb://MS-PROFESIONALES
          predicates:
            - Path=/api/v1/regiones/**

        - id: sucursal-service
          uri: lb://MS-PROFESIONALES
          predicates:
            - Path=/api/v1/sucursales/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html