server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          # Rutas para cada microservicio
            - id: boleta-service
              uri: lb://ms_agendamiento
              predicates:
                - Path=/api/v1/boleta/**, /boleta/api-docs/**

            - id: comuna-service
              uri: lb://ms_profesionales
              predicates:
                - Path=/api/v1/comuna/**, /comuna/api-docs/**

            - id: diagnostico-service
              uri: lb://ms_pacientes
              predicates:
                - Path=/api/v1/diagnostico/**, /diagnostico/api-docs/**

            - id: especialidad-service
              uri: lb://ms_profesionales
              predicates:
                - Path=/api/v1/especialidad/**, /especialidad/api-docs/**

            - id: historialDiagnostico-service
              uri: lb://ms_pacientes
              predicates:
                - Path=/api/v1/historial-diagnostico/**, /historial-diagnostico/api-docs/**

            - id: paciente-service
              uri: lb://ms_pacientes
              predicates:
                - Path=/api/v1/paciente/**, /paciente/api-docs/**

            - id: prevision-service
              uri: lb://ms_pacientes
              predicates:
                - Path=/api/v1/prevision/**, /prevision/api-docs/**

            - id: psicologo-service
              uri: lb://ms_profesionales
              predicates:
                - Path=/api/v1/psicologo/**, /psicologo/api-docs/**

            - id: region-service
              uri: lb://ms_profesionales
              predicates:
                - Path=/api/v1/region/**, /region/api-docs/**

            - id: reservaHora-service
              uri: lb://ms_agendamiento
              predicates:
                - Path=/api/v1/reserva-hora/**, /reserva-hora/api-docs/**

            - id: sucursal-service
              uri: lb://ms_profesionales
              predicates:
                - Path=/api/v1/sucursal/**, /sucursal/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Boleta
        url: /boleta/api-docs
      - name: Microservicio Comuna
        url: /comuna/api-docs
      - name: Microservicio Diagnóstico
        url: /diagnostico/api-docs
      - name: Microservicio Especialidad
        url: /especialidad/api-docs
      - name: Microservicio HistorialDiagnóstico
        url: /historial-diagnostico/api-docs
      - name: Microservicio Paciente
        url: /paciente/api-docs
      - name: Microservicio Previsión
        url: /prevision/api-docs
      - name: Microservicio Psicólogo
        url: /psicologo/api-docs
      - name: Microservicio Región
        url: /region/api-docs
      - name: Microservicio ReservaHora
        url: /reserva-hora/api-docs
      - name: Microservicio Sucursal
        url: /sucursal/api-docs
  api-docs:
    enabled: true